compile error
``airspy_usb_req.o (symbol from plugin): in function `usb_vendor_request':
(.text+0x0): multiple definition of `set_freq_params'; airspy_m0.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [../common/Makefile_M0_inc.mk:103: airspy_m0.elf] Error 1
``

removing it here doesn't cause any errors and allows it to compile for some reason